#!/usr/bin/python

import os, sys

DIRECTORY = os.path.dirname(os.path.abspath(__file__))

sys.path.insert(0, os.path.dirname(DIRECTORY))

from ether.tests import runner

runner.run(DIRECTORY, ["ether.tests.tests"],
           ["ether.tests", "ether.configs", "__init__"])

