#!/usr/bin/python -tt

"""
POST-COMMIT HOOK

 The post-commit hook is invoked after a commit.  Subversion runs
 this hook with the following ordered arguments:

   [1] REPOS-PATH   (the path to this repository)
   [2] REV          (the number of the revision just committed)
 Because the commit has already completed and cannot be undone,
 the exit code of the hook program is ignored.
"""

import sys

from optparse import OptionParser

from ether.settings import AMQP
from ether.hooks.svn import SvnHooks

from ether.publishers.log import FileLogger
from ether.publishers.amqp import BlockingAMQPPublisher, AsyncAMQPPublisher

def parse_args(argv):
    """ Commandline parser """
    parser = OptionParser(usage="%prog [options]")
    parser.add_option("--type", dest="type", metavar="<type of publisher>",
                      default="amqp-async",
                      help="amqp-blocking, amqp-async and log are supported")

    return parser.parse_args(argv)


def main(argv):
    """Script entry point."""

    options, args = parse_args(argv)

    if options.type == "amqp-async":
        publisher = AsyncAMQPPublisher(AMQP)
    elif options.type == "amqp-blocking":
        publisher = BlockingAMQPPublisher(AMQP)
    elif options.type == "log":
        publisher = FileLogger("/tmp/postcommit.log")

    SvnHooks(publisher).postcommit(args[1], args[2])
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
