#!/usr/bin/python -tt

"""
POST-COMMIT HOOK

 The post-commit hook is invoked after a commit.  Subversion runs
 this hook with the following ordered arguments:

   [1] REPOS-PATH   (the path to this repository)
   [2] REV          (the number of the revision just committed)
 Because the commit has already completed and cannot be undone,
 the exit code of the hook program is ignored.
"""

import sys
import imp

from ether.hooks.svn import SvnHook
from ether.publisher import AsyncAMQPPublisher

DEFAULT_CONFIG = "/etc/ether/svn_postcommit.conf"

def main(argv):
    """Script entry point."""

    conf = imp.load_source("conf", DEFAULT_CONFIG)
    publisher = AsyncAMQPPublisher(conf.AMQP_CONFIG)
    SvnHook(publisher, conf.REPO_CONFIG).postcommit(argv[1], argv[2])

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
