#!/usr/bin/env python -tt

"""Test Consumer."""

import sys
import imp

from ether.consumer import AsyncAMQPConsumer

DEFAULT_CONFIG = "/etc/ether/test_consumer.conf"

class TestConsumer(AsyncAMQPConsumer):
    """Test Consumer. Prints routing key and payload."""

    def process_payload(self, payload, routing_key):
        print "%s: %s" % (routing_key, payload.payload)

def main(argv):
    conf = imp.load_source("conf", DEFAULT_CONFIG)
    consumer = TestConsumer(config=conf.TEST_CONFIG)
    consumer.consume()
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
