#!/usr/bin/env python -tt

"""Test Consumer."""

from ether.consumers.amqp import AsyncConsumer

class TestConsumer(AsyncAMQPConsumer):
    """Test Consumer. Prints routing key and payload."""

    def process_payload(self, payload, routing_key):
        print "%s: %s" % (routing_key, payload.payload)

def main(argv):
    consumer = TestConsumer(config=AMQP)
    consumer.consume()
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))

