#!/usr/bin/env python -tt

"""Test Consumer."""

import sys

from ether.configs.test_consumer import TEST_CONFIG
from ether.consumers.amqp import AsyncAMQPConsumer

class TestConsumer(AsyncAMQPConsumer):
    """Test Consumer. Prints routing key and payload."""

    def process_payload(self, payload, routing_key):
        print "%s: %s" % (routing_key, payload.payload)

def main(argv):
    consumer = TestConsumer(config=TEST_CONFIG)
    consumer.consume()
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))

